name: auto-merge

on:
  pull_request_target:
  workflow_dispatch:

jobs:
  automerge:
    if: github.event.pull_request.user.login == 'dependabot[bot]'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: Read dependency update metadata
        id: metadata
        uses: dependabot/fetch-metadata@v3
      - name: Enable auto-merge for dependency updates
        if: steps.metadata.outputs.update-type == 'version-update:semver-minor'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
        run: gh pr merge --auto --squash "$PR_URL"
